# Generated by Django 2.1.7 on 2021-08-12 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210812_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 12, 14, 59, 32, 18746)),
        ),
    ]
